# Generated by Django 4.1.3 on 2022-12-28 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=15, null=True, unique=True)),
                ('profile_pic', models.ImageField(default='default_img/hr.jpg', upload_to='candidate_profile')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('cv', models.FileField(upload_to='cvs')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesWhoApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('cv', models.FileField(upload_to='resume')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_logo', models.ImageField(default='default_img/default_company_logo.png', upload_to='company_logos')),
                ('profile_pic', models.ImageField(default='default_img/hr.jpg', upload_to='hr_profile_pic')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_posted', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_posting.humanresource')),
            ],
        ),
    ]
