# Generated by Django 4.1.3 on 2022-12-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasapplied',
            name='has_applied',
            field=models.BooleanField(default=False),
        ),
    ]
