# Generated by Django 4.1.3 on 2022-11-24 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_candidate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
