# Generated by Django 4.1.3 on 2022-12-13 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_hasapplied_has_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasapplied',
            old_name='has_applied',
            new_name='applied',
        ),
    ]
