# Generated by Django 4.1.3 on 2023-01-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0002_candidateswhoapplied_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateswhoapplied',
            name='user',
        ),
    ]
