# Generated by Django 4.1.3 on 2022-12-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_rename_has_applied_hasapplied_applied'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hasapplied',
            old_name='job_id',
            new_name='job',
        ),
    ]
