# Generated by Django 4.1.3 on 2022-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0003_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(default='media_files/hr_profile/hr.jpg', upload_to='candidate_profile'),
        ),
    ]
