# Generated by Django 4.1.3 on 2022-12-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_rename_job_id_hasapplied_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HasApplied',
        ),
    ]
