# Generated by Django 4.1.3 on 2022-11-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0004_alter_candidate_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='company_logo',
            field=models.ImageField(default='media_files/hr_profile/hr.jpg', upload_to='company_logos'),
        ),
    ]
