# Generated by Django 4.1.3 on 2022-11-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0008_alter_humanresource_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='about_me',
        ),
    ]
