# Generated by Django 4.1.3 on 2022-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posting', '0009_remove_candidate_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(default='default_img/hr.jpg', upload_to='candidate_profile'),
        ),
    ]
